### ISSUE TITLE
LobbyData struct has been extended

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/ScribblersSharp#1]
https://github.com/scribble-rs/ScribblersSharp/blob/34ee4f54db5a4dd33965b22cfe3ea382a6a0fa91/ScribblersSharp/Data/HTTP/CreateLobbyResponseData.cs#L6

Struct has been extended: https://github.com/scribble-rs/scribble.rs/wiki/API-Docs#lobbydata-object

**Comment by BigETI** [comment]
https://github.com/scribble-rs/ScribblersSharp/commit/8ca723579b1d42fb02a31cf240368f92ab1ae695
