### ISSUE TITLE
NameChange event has been changed

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/ScribblersSharp#2]
Previously we sent an `update-players` event, however, this caused issues, which is why there's a custom event now.

https://github.com/scribble-rs/scribble.rs/wiki/API-Docs#name-change

**Comment by BigETI** [comment]
https://github.com/scribble-rs/ScribblersSharp/commit/8ca723579b1d42fb02a31cf240368f92ab1ae695
